-- AlterTable
ALTER TABLE "casbin_rule" ALTER COLUMN "v0" DROP NOT NULL,
ALTER COLUMN "v1" DROP NOT NULL,
ALTER COLUMN "v2" DROP NOT NULL,
ALTER COLUMN "v3" DROP NOT NULL,
ALTER COLUMN "v4" DROP NOT NULL;
